---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: loadbalancer-aks-demo
spec:
    replicas: 10
    selector: 
        matchLabels:
         name: hello-app
         type: demo-app
    template:
        metadata:
            name: hello-app
            labels:
              name: hello-app
              type: demo-app
        spec:
          containers:
          - name: hello-app
            image: k8sacademy/hello-app:2.0
            ports:
                - containerPort: 8080
          nodeSelector:
            agentpool: default 
 
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  labels:
    name: demo-app-service
    type: demo-app
spec:
   ports:
    - port: 80
      targetPort: 8080
   type: LoadBalancer
   selector:
      name: hello-app
      type: demo-app
